### ISSUE TITLE
Storage appears to be connected, but no files are shown

### ISSUE THREAD

**Issue by unalignedcoder** [owncloud/files_external_dropbox#127]
Centos 7, Apache 2.4, Owncloud v10.9.1

Trying to set this up for user admin only

I get different results with Firefox or Chrome, both fails.

Basically, the storage connection to dropbox seems fine (green light).
When I switch to Files (in Firefox), it shows no files. Only the breadcrumb at the top (Home > Files). If I go into settings, it show I use 0 B!
When I switch to Files (in Chrome), it shows only 4 folders out of 9. The dropbox mount is not among them.

The owncloud log show this:
`"user":"admin","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/admin/","message":"Cannot modify header information - headers already sent by (output started at /home/username/public_html/owncloud/lib/composer/sabre/xml/lib/Serializer/functions.php:198) at /home/username/public_html/owncloud/lib/composer/sabre/http/lib/Sapi.php#70"}`

and this:
`{\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileid' in 'where clause'\",\"Code\":\"42S22\",\"Trace\":\"#0 \home\username\public_html\owncloud\lib\composer\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php(117): PDOStatement->execute(NULL)\\n#1 \home\username\public_html\owncloud\lib\composer\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(1303): Doctrine\DBAL\Driver\PDOStatement->execute()\\n#2 \home\username\public_html\owncloud\lib\private\DB\Connection.php(191): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)\\n#3 \home\username\public_html\owncloud\apps\dav\lib\DAV\AbstractCustomPropertiesBackend.php(242): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)\\n#4 \home\username\public_html\owncloud\apps\dav\lib\DAV\FileCustomPropertiesBackend.php(158): OCA\DAV\DAV\AbstractCustomPropertiesBackend->fetchProperties('SELECT * FROM `...', Array, Array)\\n#5 \home\username\public_html\owncloud\apps\dav\lib\DAV\AbstractCustomPropertiesBackend.php(209): OCA\DAV\DAV\FileCustomPropertiesBackend->getProperties('files\admin\my-...', Object(OCA\DAV\Connector\Sabre\Directory), Array)\\n#6 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\PropertyStorage\Plugin.php(84): OCA\DAV\DAV\AbstractCustomPropertiesBackend->propFind('files\admin\my-...', Object(Sabre\DAV\PropFind))\\n#7 \home\username\public_html\owncloud\lib\composer\sabre\event\lib\WildcardEmitterTrait.php(89): Sabre\DAV\PropertyStorage\Plugin->propFind(Object(Sabre\DAV\PropFind), Object(OCA\DAV\Connector\Sabre\Directory))\\n#8 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\Server.php(1052): Sabre\DAV\Server->emit('propFind', Array)\\n#9 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\Server.php(984): Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OCA\DAV\Connector\Sabre\Directory))\\n#10 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\Server.php(1662): Sabre\DAV\Server->getPropertiesIteratorForPath('files\admin', Array, 1)\\n#11 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\Server.php(1642): Sabre\DAV\Server->writeMultiStatus(Object(Sabre\Xml\Writer), Object(Generator), false)\\n#12 \home\username\public_html\owncloud\lib\composer\sabre\http\lib\Sapi.php(83): Sabre\DAV\Server->Sabre\DAV\{closure}(*** sensitive parameters replaced ***)\\n#13 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\Server.php(490): Sabre\HTTP\Sapi::sendResponse(Object(Sabre\HTTP\Response))\\n#14 \home\username\public_html\owncloud\lib\composer\sabre\dav\lib\DAV\Server.php(253): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#15 \home\username\public_html\owncloud\apps\dav\lib\Server.php(345): Sabre\DAV\Server->start()\\n#16 \home\username\public_html\owncloud\apps\dav\appinfo\v2\remote.php(31): OCA\DAV\Server->exec()\\n#17 \home\username\public_html\owncloud\remote.php(165): require_once('\home\username\...')\\n#18 {main}\",\"File\":\"\home\username\public_html\owncloud\lib\composer\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php\",\"Line\":117}"}`

In the Firefox developer tools I get this:
`XML Parsing Error: not well-formed
Location: https://owncloud-server/remote.php/dav/files/admin/
Line Number 2, Column 3983:`
and
`Uncaught (in promise) TypeError: can't access property "permissions", this.dirInfo is undefined`

In Chrome, nothing of relevance.

To be noted that as soon as I disable external storages, or delete the dropbox mount, everything goes back to normal.

Any idea on what could be causing this?

**Comment by unalignedcoder** [comment]
The above problem seems to have been the result of migrating certain tables from a nextcloud installation. 

In particular, `oc_properties ` had a wrong schema as a result of migration, and the column `fileid` could not be found.

Restoring the original schema seem to get this app to partially work, and other webdav functionalities that were broken as well.

Now I can see all the files as well as the dropbox mount among them.

However, the dropbox mount appears to be empty, so not fully resolved.
